name: bonsai

on:
  schedule:
    - cron: "0 3 * * *" # 11:00 北京时间
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  grow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: egorthinks/git-bonsai@v1
